//! Integration tests for the Gemini adapter (p2-t3).
//!
//! Spins up a local TLS server with `tokio-rustls` using a self-signed cert
//! (generated by `rcgen`), serves a fixed gemtext response, and drives the
//! `Dispatcher` end-to-end. Verifies:
//!
//! - `Dispatcher::fetch("gemini://localhost:<port>/")` returns the expected
//!   `PageDoc`.
//! - Re-fetching reuses the TOFU pin (no prompt, no re-pin).
//! - Replacing the server's cert returns `TofuCertChanged`.

use std::sync::{Arc, Mutex};

use hypernext_core::{Block, Span, SpanRun};
use hypernext_protocol::{Dispatcher, FetchContext, FetchPolicy, GeminiAdapter};
use rcgen::{CertifiedKey, generate_simple_self_signed};
use rustls::pki_types::PrivateKeyDer;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;
use tokio_rustls::TlsAcceptor;
use url::Url;

/// A self-signed cert + key for `localhost`.
fn self_signed() -> CertifiedKey {
    generate_simple_self_signed(vec!["localhost".to_string()]).unwrap()
}

/// Build a TLS acceptor from a `CertifiedKey`.
fn acceptor(cert: &CertifiedKey) -> TlsAcceptor {
    let cert_der = cert.cert.der().clone();
    let key_der = PrivateKeyDer::try_from(cert.key_pair.serialize_der()).unwrap();
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let config = rustls::ServerConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_no_client_auth()
        .with_single_cert(vec![cert_der], key_der)
        .unwrap();
    TlsAcceptor::from(Arc::new(config))
}

/// Bind a loopback listener and return it with its port, so the client can
/// connect before the server task starts accepting.
async fn bind() -> (TcpListener, u16) {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    (listener, port)
}

/// Serve `n` TLS connections on `listener`, each reading the request line and
/// replying with `body`. The acceptor is cloned per connection.
async fn serve_n(listener: TcpListener, acceptor: TlsAcceptor, body: &'static [u8], n: usize) {
    for _ in 0..n {
        let (tcp, _) = listener.accept().await.unwrap();
        let mut tls = acceptor.clone().accept(tcp).await.unwrap();
        let mut buf = [0u8; 1024];
        let _n = tls.read(&mut buf).await.unwrap();
        tls.write_all(body).await.unwrap();
        tls.shutdown().await.unwrap();
    }
}

/// Build a `FetchContext` with an in-memory store (migrations applied) and a
/// policy that allows loopback (the test server is on 127.0.0.1).
fn ctx(policy: &FetchPolicy) -> FetchContext<'_> {
    let client = Box::leak(Box::new(reqwest::Client::new()));
    let store = Box::leak(Box::new(Mutex::new(
        hypernext_store::db::open_in_memory().unwrap(),
    )));
    FetchContext {
        http_client: client,
        cancel: tokio_util::sync::CancellationToken::new(),
        incognito: false,
        policy,
        store,
    }
}

/// The fixed gemtext body the test server serves.
const GEMTEXT: &[u8] = b"20 text/gemini\r\n# Hello\n\nWelcome to the capsule.\n";

/// A policy that allows loopback (SSRF off) so the local test server is reachable.
fn local_policy() -> FetchPolicy {
    FetchPolicy {
        block_private_network: false,
        ..Default::default()
    }
}

/// The expected `PageDoc` blocks for `GEMTEXT`.
fn expected_blocks() -> Vec<Block> {
    vec![
        Block::Heading {
            level: 1,
            text: "Hello".to_string(),
            id: None,
        },
        Block::Paragraph(Span {
            runs: vec![SpanRun {
                text: "Welcome to the capsule.".to_string(),
                style: Default::default(),
                link: None,
            }],
        }),
    ]
}

#[tokio::test]
async fn fetch_returns_expected_page_doc() {
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let server = tokio::spawn(async move { serve_n(listener, acc, GEMTEXT, 1).await });

    let mut d = Dispatcher::new();
    d.register(Box::new(GeminiAdapter::new()));
    let policy = local_policy();
    let c = ctx(&policy);

    let url = Url::parse(&format!("gemini://localhost:{port}/")).unwrap();
    let doc = d.fetch(&url, &c).await.unwrap();
    server.await.unwrap();

    assert_eq!(doc.final_url, url);
    assert_eq!(doc.title.as_deref(), Some("Hello"));
    assert_eq!(doc.blocks, expected_blocks());
}

#[tokio::test]
async fn fetch_reuses_tofu_pin_on_second_fetch() {
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    // Serve two connections with the same cert on the same listener.
    let server = tokio::spawn(async move { serve_n(listener, acc, GEMTEXT, 2).await });

    let mut d = Dispatcher::new();
    d.register(Box::new(GeminiAdapter::new()));
    let policy = local_policy();
    let c = ctx(&policy);

    let url = Url::parse(&format!("gemini://localhost:{port}/")).unwrap();

    // First fetch pins the cert.
    let doc1 = d.fetch(&url, &c).await.unwrap();
    assert_eq!(doc1.title.as_deref(), Some("Hello"));

    // Second fetch reuses the pin — no error, no re-pin.
    let doc2 = d.fetch(&url, &c).await.unwrap();
    assert_eq!(doc2.title.as_deref(), Some("Hello"));
    server.await.unwrap();
}

#[tokio::test]
async fn changed_cert_returns_tofu_cert_changed() {
    let (listener, port) = bind().await;
    let acc1 = acceptor(&self_signed());
    let acc2 = acceptor(&self_signed());
    // Serve the first connection with cert1, the second with cert2.
    let server = tokio::spawn(async move {
        // Connection 1 uses cert1, connection 2 uses cert2.
        let (tcp, _) = listener.accept().await.unwrap();
        let mut tls = acc1.accept(tcp).await.unwrap();
        let mut buf = [0u8; 1024];
        let _n = tls.read(&mut buf).await.unwrap();
        tls.write_all(GEMTEXT).await.unwrap();
        tls.shutdown().await.unwrap();

        // Connection 2: the client rejects cert2 and aborts the handshake, so
        // the server's accept fails — that is the expected outcome.
        let (tcp, _) = listener.accept().await.unwrap();
        let _ = acc2.accept(tcp).await;
    });

    let mut d = Dispatcher::new();
    d.register(Box::new(GeminiAdapter::new()));
    let policy = local_policy();
    let c = ctx(&policy);

    let url = Url::parse(&format!("gemini://localhost:{port}/")).unwrap();

    // First fetch pins cert1.
    let doc1 = d.fetch(&url, &c).await.unwrap();
    assert_eq!(doc1.title.as_deref(), Some("Hello"));

    // Second fetch sees cert2 — must fail with TofuCertChanged.
    let err = d.fetch(&url, &c).await.unwrap_err();
    assert_eq!(err.code(), "TOFU_CERT_CHANGED");
    server.await.unwrap();
}
