//! Integration tests for the Molerat adapter (p2-t5e).
//!
//! Spins up a local TLS server with `tokio-rustls` using a self-signed cert
//! (generated by `rcgen`), serves fixture Molerat wire responses, and drives
//! the `MoleratAdapter` end-to-end. Verifies: the happy path (mtxt body maps
//! to `Vec<Block>`), a redirect, a not-found, a server error, an SSRF gate, and
//! TOFU (cert-change returns `TofuCertChanged`).

use std::sync::{Arc, Mutex};

use hypernext_core::Block;
use hypernext_protocol::{FetchContext, FetchPolicy, MoleratAdapter, Protocol};
use rcgen::{CertifiedKey, generate_simple_self_signed};
use rustls::pki_types::PrivateKeyDer;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;
use tokio_rustls::TlsAcceptor;
use url::Url;

/// A self-signed cert + key for `localhost`.
fn self_signed() -> CertifiedKey {
    generate_simple_self_signed(vec!["localhost".to_string()]).unwrap()
}

/// Build a TLS acceptor from a `CertifiedKey`.
fn acceptor(cert: &CertifiedKey) -> TlsAcceptor {
    let cert_der = cert.cert.der().clone();
    let key_der = PrivateKeyDer::try_from(cert.key_pair.serialize_der()).unwrap();
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let config = rustls::ServerConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_no_client_auth()
        .with_single_cert(vec![cert_der], key_der)
        .unwrap();
    TlsAcceptor::from(Arc::new(config))
}

/// Bind a loopback listener and return it with its port.
async fn bind() -> (TcpListener, u16) {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    (listener, port)
}

/// Assert the request byte-slice's first line matches the Molerat spec
/// (https://molerat.trinket.icu/ §1.3.1): `get <host><path>...` with NO
/// `molerat://` scheme and NO `:port`.
fn assert_spec_request(bytes: &[u8]) {
    let head = String::from_utf8_lossy(bytes);
    let first_line = head.split("\r\n").next().unwrap_or("");
    assert!(
        first_line.starts_with("get "),
        "request line: {first_line:?}"
    );
    assert!(
        !first_line.contains("://"),
        "request line must not contain a scheme: {first_line:?}"
    );
    assert!(
        !first_line.contains(":2693"),
        "request line must not contain a port: {first_line:?}"
    );
}

/// Serve `n` TLS connections on `listener`, each replying with `body`.
async fn serve_n(listener: TcpListener, acceptor: TlsAcceptor, body: &'static [u8], n: usize) {
    for _ in 0..n {
        let (tcp, _) = listener.accept().await.unwrap();
        let mut tls = acceptor.clone().accept(tcp).await.unwrap();
        let mut buf = [0u8; 1024];
        let n = tls.read(&mut buf).await.unwrap();
        assert_spec_request(&buf[..n]);
        tls.write_all(body).await.unwrap();
        tls.shutdown().await.unwrap();
    }
}

/// Build a `FetchContext` with an in-memory store and a policy.
fn ctx(policy: &FetchPolicy) -> FetchContext<'static> {
    let policy = Box::leak(Box::new(policy.clone()));
    let client = Box::leak(Box::new(reqwest::Client::new()));
    let store = Box::leak(Box::new(Mutex::new(
        hypernext_store::db::open_in_memory().unwrap(),
    )));
    FetchContext {
        http_client: client,
        cancel: tokio_util::sync::CancellationToken::new(),
        incognito: false,
        policy,
        store,
    }
}

/// A policy that allows loopback (SSRF off) so the local test server is reachable.
fn local_policy() -> FetchPolicy {
    FetchPolicy {
        block_private_network: false,
        ..Default::default()
    }
}

#[tokio::test]
async fn molerat_server_answers_mtxt_fixture() {
    let fixture = include_bytes!("fixtures/molerat/index.molerat");
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let server = tokio::spawn(async move { serve_n(listener, acc, fixture, 1).await });

    let adapter = MoleratAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let url = Url::parse(&format!("molerat://localhost:{port}/")).unwrap();

    let doc = adapter.fetch(&url, &c).await.unwrap();
    server.await.unwrap();

    assert_eq!(doc.final_url, url);
    assert_eq!(doc.title.as_deref(), Some("Welcome"));
    assert!(matches!(&doc.blocks[0], Block::Heading { level: 1, text, .. } if text == "Welcome"));
    assert!(matches!(&doc.blocks[1], Block::Paragraph(_)));
    assert!(matches!(&doc.blocks[2], Block::Link { .. }));
}

#[tokio::test]
async fn molerat_server_answers_plain_fixture() {
    let fixture = include_bytes!("fixtures/molerat/plain.molerat");
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let server = tokio::spawn(async move { serve_n(listener, acc, fixture, 1).await });

    let adapter = MoleratAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let url = Url::parse(&format!("molerat://localhost:{port}/plain")).unwrap();

    let doc = adapter.fetch(&url, &c).await.unwrap();
    server.await.unwrap();
    assert_eq!(doc.blocks.len(), 1);
    assert!(matches!(&doc.blocks[0], Block::Paragraph(_)));
}

#[tokio::test]
async fn molerat_server_answers_redirect_fixture() {
    let fixture = include_bytes!("fixtures/molerat/redirect.molerat");
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let server = tokio::spawn(async move { serve_n(listener, acc, fixture, 1).await });

    let adapter = MoleratAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let url = Url::parse(&format!("molerat://localhost:{port}/old")).unwrap();

    let doc = adapter.fetch(&url, &c).await.unwrap();
    server.await.unwrap();
    assert_eq!(doc.final_url.as_str(), "molerat://example.com/moved");
}

#[tokio::test]
async fn molerat_server_answers_not_found_fixture() {
    let fixture = include_bytes!("fixtures/molerat/notfound.molerat");
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let server = tokio::spawn(async move { serve_n(listener, acc, fixture, 1).await });

    let adapter = MoleratAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let url = Url::parse(&format!("molerat://localhost:{port}/missing")).unwrap();

    let err = adapter.fetch(&url, &c).await.unwrap_err();
    server.await.unwrap();
    assert_eq!(err.code(), "NOT_FOUND");
}

#[tokio::test]
async fn molerat_server_answers_server_error_fixture() {
    let fixture = include_bytes!("fixtures/molerat/slow.molerat");
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let server = tokio::spawn(async move { serve_n(listener, acc, fixture, 1).await });

    let adapter = MoleratAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let url = Url::parse(&format!("molerat://localhost:{port}/lo")).unwrap();

    let err = adapter.fetch(&url, &c).await.unwrap_err();
    server.await.unwrap();
    assert_eq!(err.code(), "PROTOCOL_ERROR");
}

#[tokio::test]
async fn molerat_ssrf_blocks_loopback_by_default() {
    let fixture = include_bytes!("fixtures/molerat/index.molerat");
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let _server = tokio::spawn(async move { serve_n(listener, acc, fixture, 1).await });

    let adapter = MoleratAdapter::new();
    let policy = FetchPolicy::default(); // block_private_network = true
    let c = ctx(&policy);
    let url = Url::parse(&format!("molerat://localhost:{port}/")).unwrap();

    let err = adapter.fetch(&url, &c).await.unwrap_err();
    assert_eq!(err.code(), "SSRF_BLOCKED");
}

#[tokio::test]
async fn changed_cert_returns_tofu_cert_changed() {
    let fixture = include_bytes!("fixtures/molerat/index.molerat");
    let (listener, port) = bind().await;
    let acc1 = acceptor(&self_signed());
    let acc2 = acceptor(&self_signed());
    let server = tokio::spawn(async move {
        let (tcp, _) = listener.accept().await.unwrap();
        let mut tls = acc1.accept(tcp).await.unwrap();
        let mut buf = [0u8; 1024];
        let n = tls.read(&mut buf).await.unwrap();
        assert_spec_request(&buf[..n]);
        tls.write_all(fixture).await.unwrap();
        tls.shutdown().await.unwrap();

        // Connection 2: client rejects the changed cert and aborts.
        let (tcp, _) = listener.accept().await.unwrap();
        let _ = acc2.accept(tcp).await;
    });

    let adapter = MoleratAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let url = Url::parse(&format!("molerat://localhost:{port}/")).unwrap();

    // First fetch pins cert1.
    let doc1 = adapter.fetch(&url, &c).await.unwrap();
    assert_eq!(doc1.title.as_deref(), Some("Welcome"));

    // Second fetch sees cert2 — must fail with TofuCertChanged.
    let err = adapter.fetch(&url, &c).await.unwrap_err();
    assert_eq!(err.code(), "TOFU_CERT_CHANGED");
    server.await.unwrap();
}
