//! Integration tests for the Titan adapter (p2-t6).
//!
//! Spins up a local TLS server with `tokio-rustls` using a self-signed cert
//! (generated by `rcgen`), receives a Titan upload, and drives the adapter
//! end-to-end. Verifies:
//!
//! - The server receives the expected bytes.
//! - The progress callback fires at least once for a 1MB upload.
//! - A 5x server status propagates as `Error::ProtocolRejected`.
//! - Cancellation mid-upload returns `Error::Cancelled`.
//! - A changed TOFU cert returns `TofuCertChanged` (no upload attempted).

use std::sync::{Arc, Mutex};

use hypernext_protocol::{FetchContext, FetchPolicy, Protocol, PublishPayload, TitanAdapter};
use rcgen::{CertifiedKey, generate_simple_self_signed};
use rustls::pki_types::PrivateKeyDer;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpListener;
use tokio_rustls::TlsAcceptor;
use url::Url;

/// A self-signed cert + key for `localhost`.
fn self_signed() -> CertifiedKey {
    generate_simple_self_signed(vec!["localhost".to_string()]).unwrap()
}

/// Build a TLS acceptor from a `CertifiedKey`.
fn acceptor(cert: &CertifiedKey) -> TlsAcceptor {
    let cert_der = cert.cert.der().clone();
    let key_der = PrivateKeyDer::try_from(cert.key_pair.serialize_der()).unwrap();
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let config = rustls::ServerConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_no_client_auth()
        .with_single_cert(vec![cert_der], key_der)
        .unwrap();
    TlsAcceptor::from(Arc::new(config))
}

/// Bind a loopback listener and return it with its port.
async fn bind() -> (TcpListener, u16) {
    let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    (listener, port)
}

/// Build a `FetchContext` with an in-memory store and a policy that allows
/// loopback (the test server is on 127.0.0.1).
fn ctx(policy: &FetchPolicy) -> FetchContext<'_> {
    let client = Box::leak(Box::new(reqwest::Client::new()));
    let store = Box::leak(Box::new(Mutex::new(
        hypernext_store::db::open_in_memory().unwrap(),
    )));
    FetchContext {
        http_client: client,
        cancel: tokio_util::sync::CancellationToken::new(),
        incognito: false,
        policy,
        store,
    }
}

/// A policy that allows loopback (SSRF off) so the local test server is reachable.
fn local_policy() -> FetchPolicy {
    FetchPolicy {
        block_private_network: false,
        ..Default::default()
    }
}

/// Serve one TLS connection, reading the full Titan request (header + body)
/// and replying with `response`. The body length is parsed from the `size=`
/// field in the header (the client does not half-close before reading the
/// response, so the server must not wait for EOF). Returns the received bytes
/// via `received`.
async fn serve_one(
    listener: TcpListener,
    acceptor: TlsAcceptor,
    response: &'static [u8],
    received: Arc<Mutex<Vec<u8>>>,
) {
    let (tcp, _) = listener.accept().await.unwrap();
    let mut tls = acceptor.accept(tcp).await.unwrap();

    // Read the header up to the first CRLF.
    let mut header = Vec::new();
    let mut byte = [0u8; 1];
    loop {
        let n = tls.read(&mut byte).await.unwrap();
        if n == 0 {
            break;
        }
        header.push(byte[0]);
        if header.ends_with(b"\r\n") {
            break;
        }
    }
    let header_str = String::from_utf8_lossy(&header);
    let size = parse_size(&header_str).unwrap_or(0);

    // Read exactly `size` body bytes.
    let mut body = vec![0u8; size];
    let mut read = 0usize;
    while read < size {
        let n = tls.read(&mut body[read..]).await.unwrap();
        if n == 0 {
            break;
        }
        read += n;
    }
    body.truncate(read);

    let mut buf = header;
    buf.extend_from_slice(&body);
    *received.lock().unwrap() = buf;

    tls.write_all(response).await.unwrap();
    tls.shutdown().await.unwrap();
}

/// Extract the `size=<n>` field from a Titan request header.
fn parse_size(header: &str) -> Option<usize> {
    let rest = header.split(';').find(|p| p.starts_with("size="))?;
    rest.strip_prefix("size=")?.parse().ok()
}

/// The success response a Titan server returns after accepting an upload.
const SUCCESS: &[u8] = b"20 text/plain\r\nok";

#[tokio::test]
async fn server_receives_expected_bytes() {
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let received: Arc<Mutex<Vec<u8>>> = Arc::new(Mutex::new(Vec::new()));
    let r2 = Arc::clone(&received);
    let server = tokio::spawn(async move { serve_one(listener, acc, SUCCESS, r2).await });

    let adapter = TitanAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let content = b"hello titan".to_vec();
    let url = Url::parse(&format!("titan://localhost:{port}/upload")).unwrap();
    let payload = PublishPayload {
        mime: "text/plain".to_string(),
        content: content.clone(),
    };

    let result = adapter.publish(&url, &payload, &c).await.unwrap();
    server.await.unwrap();

    assert_eq!(result.url.as_ref(), Some(&url));
    let got = received.lock().unwrap().clone();
    // Header: titan://localhost:port/upload;size=11;mime=text/plain\r\n then body.
    let header = format!("titan://localhost:{port}/upload;size=11;mime=text/plain\r\n");
    assert!(got.starts_with(header.as_bytes()), "header mismatch");
    assert_eq!(&got[header.len()..], &content[..]);
}

#[tokio::test]
async fn progress_fires_at_least_once_for_1mb_upload() {
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let received: Arc<Mutex<Vec<u8>>> = Arc::new(Mutex::new(Vec::new()));
    let r2 = Arc::clone(&received);
    let server = tokio::spawn(async move { serve_one(listener, acc, SUCCESS, r2).await });

    let progress = Arc::new(Mutex::new(0u64));
    let p2 = Arc::clone(&progress);
    let adapter = TitanAdapter::new().with_progress(move |n| {
        *p2.lock().unwrap() = n;
    });
    let policy = local_policy();
    let c = ctx(&policy);
    let content = vec![b'x'; 1024 * 1024]; // 1MB
    let url = Url::parse(&format!("titan://localhost:{port}/upload")).unwrap();
    let payload = PublishPayload {
        mime: "application/octet-stream".to_string(),
        content,
    };

    adapter.publish(&url, &payload, &c).await.unwrap();
    server.await.unwrap();

    let last = *progress.lock().unwrap();
    assert!(
        last >= 32 * 1024,
        "progress should fire at least once, got {last}"
    );
}

#[tokio::test]
async fn server_5x_status_propagates_as_protocol_rejected() {
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    let received: Arc<Mutex<Vec<u8>>> = Arc::new(Mutex::new(Vec::new()));
    let r2 = Arc::clone(&received);
    let server =
        tokio::spawn(async move { serve_one(listener, acc, b"51 not found\r\n", r2).await });

    let adapter = TitanAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let url = Url::parse(&format!("titan://localhost:{port}/upload")).unwrap();
    let payload = PublishPayload {
        mime: "text/plain".to_string(),
        content: b"data".to_vec(),
    };

    let err = adapter.publish(&url, &payload, &c).await.unwrap_err();
    server.await.unwrap();
    assert_eq!(err.code(), "PROTOCOL_REJECTED");
}

#[tokio::test]
async fn cancellation_mid_upload_returns_cancelled() {
    let (listener, port) = bind().await;
    let acc = acceptor(&self_signed());
    // Server accepts the connection but never reads, so the client blocks on
    // write and the cancel token fires.
    let server = tokio::spawn(async move {
        let (tcp, _) = listener.accept().await.unwrap();
        let _tls = acc.accept(tcp).await.unwrap();
        // Hold the connection open without reading.
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    });

    let adapter = TitanAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    c.cancel.cancel();
    let url = Url::parse(&format!("titan://localhost:{port}/upload")).unwrap();
    let payload = PublishPayload {
        mime: "text/plain".to_string(),
        content: vec![b'x'; 1024 * 1024],
    };

    let err = adapter.publish(&url, &payload, &c).await.unwrap_err();
    assert_eq!(err.code(), "CANCELLED");
    server.abort();
}

#[tokio::test]
async fn changed_cert_returns_tofu_cert_changed_no_upload() {
    let (listener, port) = bind().await;
    let acc1 = acceptor(&self_signed());
    let acc2 = acceptor(&self_signed());
    let server = tokio::spawn(async move {
        // Connection 1 uses cert1 (pins it).
        let (tcp, _) = listener.accept().await.unwrap();
        let mut tls = acc1.accept(tcp).await.unwrap();
        let mut header = Vec::new();
        let mut byte = [0u8; 1];
        loop {
            let n = tls.read(&mut byte).await.unwrap();
            if n == 0 {
                break;
            }
            header.push(byte[0]);
            if header.ends_with(b"\r\n") {
                break;
            }
        }
        let header_str = String::from_utf8_lossy(&header);
        let size = parse_size(&header_str).unwrap_or(0);
        let mut body = vec![0u8; size];
        let mut read = 0usize;
        while read < size {
            let n = tls.read(&mut body[read..]).await.unwrap();
            if n == 0 {
                break;
            }
            read += n;
        }
        tls.write_all(SUCCESS).await.unwrap();
        tls.shutdown().await.unwrap();

        // Connection 2: the client rejects cert2 and aborts the handshake.
        let (tcp, _) = listener.accept().await.unwrap();
        let _ = acc2.accept(tcp).await;
    });

    let adapter = TitanAdapter::new();
    let policy = local_policy();
    let c = ctx(&policy);
    let url = Url::parse(&format!("titan://localhost:{port}/upload")).unwrap();
    let payload = PublishPayload {
        mime: "text/plain".to_string(),
        content: b"data".to_vec(),
    };

    // First upload pins cert1.
    adapter.publish(&url, &payload, &c).await.unwrap();

    // Second upload sees cert2 — must fail with TofuCertChanged.
    let err = adapter.publish(&url, &payload, &c).await.unwrap_err();
    assert_eq!(err.code(), "TOFU_CERT_CHANGED");
    server.await.unwrap();
}
